//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praxicloud.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("praxicloud.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:s}: {1} -&gt; count: {2}, min: {3}, max: {4}, avg: {5}, sum: {6}, std: {7}, P50: {8}, P90: {9}, P95: {10}, P99: {11}.
        /// </summary>
        internal static string AggregateFormatString {
            get {
                return ResourceManager.GetString("AggregateFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must be assignable to {1}..
        /// </summary>
        internal static string AssignableFrom {
            get {
                return ResourceManager.GetString("AssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must have at least {1} elements..
        /// </summary>
        internal static string AtLeastElementCount {
            get {
                return ResourceManager.GetString("AtLeastElementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must be in the range of {1} and {2}.
        /// </summary>
        internal static string CannotBeOutOfRange {
            get {
                return ResourceManager.GetString("CannotBeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be an empty collection..
        /// </summary>
        internal static string CollectionCannotBeEmpty {
            get {
                return ResourceManager.GetString("CollectionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} did not satisfy the required condition..
        /// </summary>
        internal static string ConditionNotSatisfied {
            get {
                return ResourceManager.GetString("ConditionNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} is not a valid directory name or does not exist..
        /// </summary>
        internal static string DirectoryExists {
            get {
                return ResourceManager.GetString("DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} is not a valid directory name or exists..
        /// </summary>
        internal static string DirectoryNotExists {
            get {
                return ResourceManager.GetString("DirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must have at least {1} elements but it has {2}..
        /// </summary>
        internal static string ElementCountAtLeast {
            get {
                return ResourceManager.GetString("ElementCountAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must have between {1} and {2} elements but it has {3}..
        /// </summary>
        internal static string ElementCountInRange {
            get {
                return ResourceManager.GetString("ElementCountInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} is not a valid file name or does not exist..
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} is not a valid file name or exists..
        /// </summary>
        internal static string FileNotExists {
            get {
                return ResourceManager.GetString("FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be null and the index must be less than the number of elements..
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} was expected to have a value of {1}..
        /// </summary>
        internal static string InvalidArgumentValue {
            get {
                return ResourceManager.GetString("InvalidArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} contained a value that was not defined in the enumeration..
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The observer passed to the Subscribe method must be of type Observer&lt;T&gt;..
        /// </summary>
        internal static string InvalidObserverType {
            get {
                return ResourceManager.GetString("InvalidObserverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be the default value for the type..
        /// </summary>
        internal static string NotDefault {
            get {
                return ResourceManager.GetString("NotDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must contain an element {1}..
        /// </summary>
        internal static string NotInArray {
            get {
                return ResourceManager.GetString("NotInArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must contain an element {1}..
        /// </summary>
        internal static string NotInCollection {
            get {
                return ResourceManager.GetString("NotInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be less than {1}..
        /// </summary>
        internal static string NotLessThan {
            get {
                return ResourceManager.GetString("NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be more than {1}..
        /// </summary>
        internal static string NotMoreThan {
            get {
                return ResourceManager.GetString("NotMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be null..
        /// </summary>
        internal static string NotNull {
            get {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be a null or empty string..
        /// </summary>
        internal static string NotNullOrEmpty {
            get {
                return ResourceManager.GetString("NotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be a null or empty or all whitespace string..
        /// </summary>
        internal static string NotNullOrWhitespace {
            get {
                return ResourceManager.GetString("NotNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} cannot be null and the offset +count must be less than the number of elements..
        /// </summary>
        internal static string SegmentOutOfRange {
            get {
                return ResourceManager.GetString("SegmentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} must be a string between the length of {1} and {2} inclusively.
        /// </summary>
        internal static string StringLengthInRange {
            get {
                return ResourceManager.GetString("StringLengthInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} does not match the pattern {1}..
        /// </summary>
        internal static string StringMustMatchRegex {
            get {
                return ResourceManager.GetString("StringMustMatchRegex", resourceCulture);
            }
        }
    }
}
